/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/clinics/{clinic_id}/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_v1_clinics__clinic_id__analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clinics/{clinic_id}/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Calls */
        get: operations["list_calls_v1_clinics__clinic_id__calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clinics/{clinic_id}/calls/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Call Detail */
        get: operations["call_detail_v1_clinics__clinic_id__calls__call_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clinics/{clinic_id}/calls/{call_id}/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Workflow
         * @description Change a call's workflow status. ``If-Match`` carries the version the user saw (two
         *     receptionists can't silently overwrite each other); ``Idempotency-Key`` makes retries safe.
         */
        post: operations["update_workflow_v1_clinics__clinic_id__calls__call_id__workflow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clinics/{clinic_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clinic Events */
        get: operations["clinic_events_v1_clinics__clinic_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clinics/{clinic_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage
         * @description Billing view (admins and owners): per-day calls, minutes and voice-provider cost, rolled
         *     up hourly by ops-worker. Days without calls are omitted.
         */
        get: operations["usage_v1_clinics__clinic_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsSummary */
        AnalyticsSummary: {
            /** By Day */
            by_day: components["schemas"]["DayCount"][];
            /** By Hour */
            by_hour: components["schemas"]["HourCount"][];
            /** By Weekday */
            by_weekday: components["schemas"]["WeekdayCount"][];
            /**
             * Clinic Id
             * Format: uuid
             */
            clinic_id: string;
            /**
             * From
             * Format: date
             */
            from: string;
            /** Sentiment */
            sentiment: {
                [key: string]: number;
            };
            /** Timezone */
            timezone: string;
            /**
             * To
             * Format: date
             */
            to: string;
            /** Top Intents */
            top_intents: components["schemas"]["IntentCount"][];
            totals: components["schemas"]["Totals"];
            /** Workflow */
            workflow: {
                [key: string]: number;
            };
        };
        /** CallDetail */
        CallDetail: {
            call: components["schemas"]["CallRecord"];
            /** Interactions */
            interactions: components["schemas"]["Interaction"][];
            /** Messages */
            messages: components["schemas"]["CapturedMessage"][];
        };
        /** CallPage */
        CallPage: {
            /** Items */
            items: components["schemas"]["CallSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** CallRecord */
        CallRecord: {
            /** Analyzed At */
            analyzed_at: string | null;
            /**
             * Cost Usd
             * @description Voice-provider cost in US dollars, as a decimal string
             */
            cost_usd: string | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "inbound" | "outbound";
            /** Disconnection Reason */
            disconnection_reason: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Ended At */
            ended_at: string | null;
            /** From Number */
            from_number: string | null;
            /**
             * Has Urgent Message
             * @description The caller left a message the voice agent flagged as urgent
             */
            has_urgent_message: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Intent */
            intent: string | null;
            /** Is Priority */
            is_priority: boolean;
            /** Is Reception Action */
            is_reception_action: boolean;
            /**
             * Local Date
             * @description Call date in the clinic's own timezone
             */
            local_date: string | null;
            /** Local Hour */
            local_hour: number | null;
            /** Provider Call Id */
            provider_call_id: string;
            /** Sentiment */
            sentiment: string | null;
            /** Started At */
            started_at: string | null;
            /** Summary */
            summary: string | null;
            /** To Number */
            to_number: string | null;
            /**
             * Transcript
             * @description Plain text. Never render it as HTML or Markdown.
             */
            transcript: string | null;
            /** Version */
            version: number;
            /**
             * Workflow Status
             * @enum {string}
             */
            workflow_status: "pending" | "following_up" | "addressed" | "no_action_needed";
        };
        /**
         * CallSummary
         * @description One row of the call list: enough to triage, without the transcript.
         */
        CallSummary: {
            /** Duration Seconds */
            duration_seconds: number | null;
            /** From Number */
            from_number: string | null;
            /**
             * Has Urgent Message
             * @description The caller left a message the voice agent flagged as urgent
             */
            has_urgent_message: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Intent */
            intent: string | null;
            /** Is Priority */
            is_priority: boolean;
            /** Is Reception Action */
            is_reception_action: boolean;
            /** Started At */
            started_at: string | null;
            /** Summary */
            summary: string | null;
            /** Version */
            version: number;
            /**
             * Workflow Status
             * @enum {string}
             */
            workflow_status: "pending" | "following_up" | "addressed" | "no_action_needed";
        };
        /** CapturedMessage */
        CapturedMessage: {
            /** Callback Number */
            callback_number: string | null;
            /** Category */
            category: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Detail
             * @description What the caller said. Plain text; never render as HTML.
             */
            detail: string;
            /** Urgent */
            urgent: boolean;
        };
        /** ClinicAccess */
        ClinicAccess: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "receptionist" | "admin" | "owner";
            /** Slug */
            slug: string;
            /** Timezone */
            timezone: string;
        };
        /** DayCount */
        DayCount: {
            /** Calls */
            calls: number;
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HourCount */
        HourCount: {
            /** Calls */
            calls: number;
            /** Hour */
            hour: number;
        };
        /** IntentCount */
        IntentCount: {
            /** Calls */
            calls: number;
            /** Intent */
            intent: string;
        };
        /** Interaction */
        Interaction: {
            /** Action Type */
            action_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Note */
            note: string | null;
            /** Status From */
            status_from: string | null;
            /** Status To */
            status_to: string | null;
        };
        /** Me */
        Me: {
            /** Clinics */
            clinics: components["schemas"]["ClinicAccess"][];
            /** Email */
            email: string;
        };
        /** Totals */
        Totals: {
            /** Avg Duration Seconds */
            avg_duration_seconds: number | null;
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: string;
            /** Priority */
            priority: number;
            /** Reception Action */
            reception_action: number;
            /** Total Duration Seconds */
            total_duration_seconds: number;
        };
        /** UsageDay */
        UsageDay: {
            /** Calls */
            calls: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Minutes */
            minutes: string;
            /** Provider Cost Usd */
            provider_cost_usd: string;
        };
        /** UsageReport */
        UsageReport: {
            /**
             * Clinic Id
             * Format: uuid
             */
            clinic_id: string;
            /** Days */
            days: components["schemas"]["UsageDay"][];
            /**
             * From
             * Format: date
             */
            from: string;
            /**
             * To
             * Format: date
             */
            to: string;
            totals: components["schemas"]["UsageTotals"];
        };
        /** UsageTotals */
        UsageTotals: {
            /** Calls */
            calls: number;
            /** Minutes */
            minutes: string;
            /** Provider Cost Usd */
            provider_cost_usd: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeekdayCount */
        WeekdayCount: {
            /** Calls */
            calls: number;
            /**
             * Weekday
             * @description Monday = 0
             */
            weekday: number;
        };
        /** WorkflowAction */
        WorkflowAction: {
            /** Note */
            note?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "following_up" | "addressed" | "no_action_needed";
        };
        /** WorkflowResult */
        WorkflowResult: {
            /**
             * Call Id
             * Format: uuid
             */
            call_id: string;
            /** Version */
            version: number;
            /**
             * Workflow Status
             * @enum {string}
             */
            workflow_status: "pending" | "following_up" | "addressed" | "no_action_needed";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    summary_v1_clinics__clinic_id__analytics_summary_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path: {
                clinic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calls_v1_clinics__clinic_id__calls_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                /** @description Only calls still to do (pending or following up) */
                open_only?: boolean;
            };
            header?: never;
            path: {
                clinic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    call_detail_v1_clinics__clinic_id__calls__call_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: string;
                call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workflow_v1_clinics__clinic_id__calls__call_id__workflow_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "If-Match": number;
            };
            path: {
                clinic_id: string;
                call_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clinic_events_v1_clinics__clinic_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                clinic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usage_v1_clinics__clinic_id__usage_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path: {
                clinic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
}
